insert into public.remedies (
  slug,
  name,
  name_latin,
  category,
  summary,
  traditional_use,
  preparation_steps,
  ingredients,
  symptoms,
  dosage_note,
  contraindications,
  interactions,
  pregnancy_warning,
  pregnancy_warning_text,
  allergy_note,
  sources,
  is_teaser
)
values
(
  'chamomile',
  'Chamomile',
  'Matricaria recutita',
  'Sleep',
  'A gentle flowering herb traditionally used to calm the nerves and ease uneasy digestion.',
  'Chamomile has long been used in household herbal practice for its soft, settling character. Traditionally it is prepared as a warm infusion when the body feels tense, restless, or unsettled after food.',
  '[{"title":"Measure","text":"Use 2 heaped teaspoons of dried flowers for one cup."},{"title":"Infuse","text":"Pour freshly boiled water over the herb and cover for 10 minutes."},{"title":"Serve","text":"Strain and drink warm. Honey may be added after the tea cools slightly."}]'::jsonb,
  array['Dried chamomile flowers', 'Freshly boiled water', 'Raw honey, optional'],
  array['restlessness', 'evening tension', 'post-meal heaviness'],
  'Traditional range: 1 to 3 cups daily, depending on the preparation and tolerance.',
  array['Do not use if you have a known allergy to plants in the Asteraceae family.'],
  array['May intensify the effects of sedative medicines and coumarin anticoagulants.'],
  true,
  'Pregnancy: keep to ordinary dietary amounts unless a qualified practitioner advises otherwise.',
  'Possible cross-reaction with ragweed, chrysanthemums, marigolds, and daisies.',
  array['European Medicines Agency herbal monograph', 'British Herbal Pharmacopoeia', 'Commission E monograph collection'],
  false
),
(
  'ginger',
  'Ginger',
  'Zingiber officinale',
  'Digestive',
  'A warming root traditionally used to settle the stomach and support circulation.',
  'Ginger has been used in kitchens and herbal practice alike as a warming, aromatic root. Traditionally it is prepared when the body feels cold, sluggish, or unsettled after travel or meals.',
  '[{"title":"Slice","text":"Cut a small piece of fresh root or use a teaspoon of dried slices."},{"title":"Simmer","text":"Steep in hot water for 10 to 15 minutes to draw out the aroma."},{"title":"Balance","text":"Drink plain or with a little honey or lemon if the flavor feels too sharp."}]'::jsonb,
  array['Fresh ginger root or dried ginger slices', 'Water', 'Honey or lemon, optional'],
  array['nausea', 'travel sickness', 'cold digestion'],
  'Traditional range: small cups through the day; keep preparations modest and conservative.',
  array['Use caution if you have a very sensitive stomach or active gastric irritation.'],
  array['May affect anticoagulants and blood-sugar-lowering medicines.'],
  true,
  'Pregnancy: use only conservative dietary amounts and seek guidance for concentrated preparations.',
  'Uncommon, but stop use if mouth or skin irritation appears.',
  array['Traditional European herbal practice', 'Commission E', 'Modern herb monographs'],
  false
),
(
  'elderberry',
  'Elderberry',
  'Sambucus nigra',
  'Immunity',
  'A dark berry preparation traditionally used in seasonal folk practice.',
  'Elderberry has a long folk history as a seasonal remedy. Traditionally it is prepared as a syrup or decoction when people want a warming, dark berry infusion during the cold months.',
  '[{"title":"Cook","text":"Simmer the berries thoroughly rather than using them raw."},{"title":"Strain","text":"Press through a sieve to remove skins and seeds."},{"title":"Store","text":"Keep refrigerated and use only a small serving at a time."}]'::jsonb,
  array['Cooked elderberries', 'Water', 'Optional honey', 'Optional warming spices'],
  array['seasonal weariness', 'cool weather routines', 'convalescent care'],
  'Traditional range only; keep servings small and preparation thorough.',
  array['Do not use raw berries, leaves, or stems.'],
  array['Use caution alongside immunosuppressive medicines and diuretics.'],
  true,
  'Pregnancy: use only well-prepared, conservative servings and avoid raw material.',
  'Stop use if digestive upset or rash appears.',
  array['Folk herb references', 'Herbal monographs', 'Traditional syrup preparations'],
  true
),
(
  'valerian',
  'Valerian',
  'Valeriana officinalis',
  'Sleep',
  'A root traditionally used for settled evenings and calmer night rest.',
  'Valerian has been used for generations in quiet evening preparations. Traditionally it is taken when a person wants a stronger, earthy herb for winding down rather than stimulation.',
  '[{"title":"Grind","text":"Lightly bruise the root to expose the aroma before steeping."},{"title":"Steep","text":"Infuse in hot water for 10 to 15 minutes, covered."},{"title":"Use at night","text":"Drink in the evening and keep the rest of the routine calm and simple."}]'::jsonb,
  array['Dried valerian root', 'Hot water'],
  array['restless evenings', 'tension', 'sleep ritual support'],
  'Traditional range: modest evening servings only.',
  array['Do not combine with other strongly sedating preparations without guidance.'],
  array['May intensify sedative medicines, alcohol, and certain sleep aids.'],
  true,
  'Pregnancy: avoid concentrated use unless a qualified practitioner approves it.',
  'Earthy odor is normal; stop if adverse reactions appear.',
  array['European herbal references', 'Traditional sleep preparations', 'Herbal monographs'],
  false
),
(
  'peppermint',
  'Peppermint',
  'Mentha × piperita',
  'Digestive',
  'A cooling aromatic herb traditionally used after meals and for a clear, bright mouthfeel.',
  'Peppermint is a familiar household herb, traditionally used after meals and in refreshing infusions. Its bright aroma is often chosen when the body feels heavy or overfull.',
  '[{"title":"Crush","text":"Gently bruise the leaves before steeping."},{"title":"Infuse","text":"Cover with hot water for 5 to 8 minutes to keep the flavor lively."},{"title":"Drink","text":"Sip slowly after food or during the day as a cooling herbal cup."}]'::jsonb,
  array['Peppermint leaves', 'Hot water'],
  array['heaviness after meals', 'bloating', 'taste fatigue'],
  'Traditional range: a cup after meals or as needed for a short, conservative run.',
  array['Use caution if reflux tends to worsen with minty preparations.'],
  array['May alter how some antacids and reflux medicines feel subjectively.'],
  true,
  'Pregnancy: ordinary culinary use is different from concentrated herbal use; keep preparations modest.',
  'May irritate sensitive mouths or throats if overly concentrated.',
  array['Household herbal practice', 'Modern monographs', 'Traditional digestive teas'],
  false
)
on conflict (slug) do update set
  name = excluded.name,
  name_latin = excluded.name_latin,
  category = excluded.category,
  summary = excluded.summary,
  traditional_use = excluded.traditional_use,
  preparation_steps = excluded.preparation_steps,
  ingredients = excluded.ingredients,
  symptoms = excluded.symptoms,
  dosage_note = excluded.dosage_note,
  contraindications = excluded.contraindications,
  interactions = excluded.interactions,
  pregnancy_warning = excluded.pregnancy_warning,
  pregnancy_warning_text = excluded.pregnancy_warning_text,
  allergy_note = excluded.allergy_note,
  sources = excluded.sources,
  is_teaser = excluded.is_teaser,
  updated_at = now();

